image: oberbichler/ubuntu-dev

before_script: 
    - export PATH=~/miniconda/bin:$PATH
    - conda install numpy
    - conda install pyqt

stages:
    - test

test:
    stage: test
    script:
        - echo "Testing"
        - pwd
        - python3 --version
        - python3 -m unittest discover
    tags:
        - test
