stages:
    - test

test:
    stage: test
    script:
        - echo "Testing"
        - pwd
        - whoami
        - python3 --version
        - python3 -m pip install PyQt5
        - python3 -m unittest discover -p 'test_*.py'
    tags:
        - sh_test
